# Generated by Django 4.0.4 on 2022-05-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carusel',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carusel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
